// Local content adapter: reads the seed generated by scripts/normalize-odoo.mjs.
// Swapped for lib/content/sanity.ts when CONTENT_SOURCE=sanity (see ./index.ts).
import productsData from "@/content/products.json";
import categoriesData from "@/content/categories.json";
import brandsData from "@/content/brands.json";
import type {
  Brand,
  Category,
  ContentSource,
  Product,
  ProductFilter,
} from "./types";

const products = productsData as unknown as Product[];
const categories = (categoriesData as unknown as Category[])
  .slice()
  .sort((a, b) => a.order - b.order);
const brands = brandsData as unknown as Brand[];

function matchesAttrs(p: Product, attrs: ProductFilter["attrs"]): boolean {
  if (!attrs) return true;
  return Object.entries(attrs).every(([key, value]) => {
    if (value === undefined || value === "") return true;
    const actual = p.specs[key as keyof Product["specs"]];
    if (actual === undefined) return false;
    return String(actual).toLowerCase() === String(value).toLowerCase();
  });
}

export const localSource: ContentSource = {
  async getCategories() {
    return categories;
  },

  async getCategory(slug) {
    return categories.find((c) => c.slug === slug) ?? null;
  },

  async getProducts(filter: ProductFilter = {}) {
    return products.filter((p) => {
      if (!p.active) return false;
      if (filter.category && p.category !== filter.category) return false;
      if (filter.brand && p.brand !== filter.brand) return false;
      if (!matchesAttrs(p, filter.attrs)) return false;
      return true;
    });
  },

  async getProduct(slug) {
    return products.find((p) => p.slug === slug) ?? null;
  },

  async getRelatedProducts(product, limit = 4) {
    return products
      .filter(
        (p) =>
          p.active &&
          p.slug !== product.slug &&
          p.category === product.category,
      )
      .sort((a, b) => {
        // prefer same brand, then products with a real photo
        const brandScore = (x: Product) => (x.brand === product.brand ? 1 : 0);
        const imgScore = (x: Product) => (x.images.length ? 1 : 0);
        return (
          brandScore(b) - brandScore(a) || imgScore(b) - imgScore(a)
        );
      })
      .slice(0, limit);
  },

  async getBrand(slug) {
    return brands.find((b) => b.slug === slug) ?? null;
  },

  async getBrands() {
    return brands;
  },
};
